### ISSUE TITLE
Show runtime values for failed tests

### ISSUE THREAD

**Issue by BNAndras** [RickBarretto/unitt#6]
```
❌ - assert that appending binaries with integer is working
     assertion : [as binary 1 = append b 1]
```

It would be helpful if the message indicates what the value was at runtime that failed the assertion.

**Comment by RickBarretto** [comment]
> It would be helpful if the message indicates what the value was at runtime that failed the assertion.

That is something I'm trying to figure out since the first day how to do it, lol!
Basically, let me give you a example to you understand why that a not so easy thing to solve:

## Example

```
list: [0 1 2 3]
list2: [4 5 6]
assert -> list = list2
``` 

If I want to show each value, I will need to evaluate it. But that is not simple as run `do` or `@` because this will return `false`.
So, I need some way to read each readable value. Notice that I can't take the `var` of a symbol:

```
$> l: [1 2 3 4]

$> l2: [4 5 7]

$> blk: -> l = l2

$> blk
=> [l = l2]

$> @blk
=> [false]

$> loop blk => var
>> Runtime | cannot perform var -> :symbol
     error | incorrect argument type for first parameter
           | accepts :string :word :literal :pathliteral
=> [1 2 3 4]
```

## My next steps

Doing some experiments while writing this comment, what I have in mind is:
1. Select items that are `:string`, `:word`, `:literal`, `:pathliteral`
2. Save the indexes in a map table
3. Prints the runtime value of words in that map, and prints the static value for items that are not in.

**Comment by RickBarretto** [comment]
BTW, just a initial draft:

```
$> allowed: [:string :word :literal :pathliteral]

$> blk | select 'el -> in? type el allowed | map => var
=> [[1 2 3 4] [4 5 7]]
```
